(function(g){var window=this;'use strict';var $3=function(a){a.ra("cardstatechange",a.Bk()&&a.Po()?1:0)},a4=function(a,b){var c=g.Wa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Chb=function(a){var b=g.yr(a);
a=g.Br(a);return new g.nr(b.x,b.y,a.width,a.height)},Dhb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.mD(a,b,function(){g.nD(e);c.apply(a,arguments)},d)},d4=function(a){a=g.ab(a);
delete b4[a];g.jd(b4)&&c4&&c4.stop()},Fhb=function(){c4||(c4=new g.Ut(function(){Ehb()},20));
var a=c4;a.isActive()||a.start()},Ehb=function(){var a=g.eb();
g.Tc(b4,function(b){Ghb(b,a)});
g.jd(b4)||Fhb()},e4=function(a,b,c,d){g.nu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.S=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Ghb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Hhb(a,a.progress);1==a.progress?(a.j=0,d4(a),a.onFinish(),a.ir()):a.isPlaying()&&a.AK()},Hhb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.S[c]-a.B[c])*b+a.B[c]},Ihb=function(a,b){g.xb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},f4=function(a,b,c,d,e){e4.call(this,b,c,d,e);
this.element=a},Jhb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
f4.call(this,a,b,c,d,e)},Khb=function(a){return Math.pow(a,3)},Lhb=function(a){return 3*a*a-2*a*a*a},Mhb=function(a){g.J.call(this);
this.B=a||window;this.j=[]},g4=function(a){return a.baseUrl||null},h4=function(a,b){return g.ks(g.Up(a,b),function(c){return!!c})},Nhb=function(a,b,c){function d(pa){var ia=pa.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var Aa=f(ia.unsubscribedButtonText),X=f(ia.subscribedButtonText);if(ia.subscribed){var wa=f(ia.subscriberCountWithUnsubscribeText);var ca=f(ia.subscriberCountText)}else wa=f(ia.subscriberCountText),ca=f(ia.subscriberCountWithSubscribeText);var Ra=null;if(pa.signinEndpoint){Ra=a4(pa,"signinEndpoint","webNavigationEndpointData","url");if(!Ra){var x,V;Ra=null==(V=g.T(null==(x=ia.signInEndpoint)?void 0:x.commandMetadata,g.S2))?void 0:
V.url}if(!Ra)return null}return Aa&&(X||Ra)?{subscribed:ia.subscribed,subscribeText:Aa,subscribeCount:wa,unsubscribeText:X,unsubscribeCount:ca,enabled:ia.enabled,signinUrl:Ra,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var ia=[],Aa=pa.videoId;Aa&&ia.push("v="+Aa);(Aa=pa.playlistId)&&ia.push("list="+Aa);(pa=pa.startTimeSeconds)&&ia.push("t="+pa);return"/watch?"+ia.join("&")}}
function f(pa){if(!pa)return null;var ia=pa.simpleText;return ia?ia:pa.runs?g.Up(pa.runs,function(Aa){return Aa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,w=null,y=!1,C=null,H=null,G=null,I=null,P=null,R=null;if("VIDEO"===h)g.T(l,g.WG)?m=g.T(l,g.WG).url:(R=g.T(l,g.DT),m=e(R)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.T(l,g.WG)?m=g.T(l,g.WG).url:(R=g.T(l,g.DT),m=e(R)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(y=a4(l,"browseEndpoint","browseId"))w=y,m="/channel/"+w;n=!1;q="new";(y=!!b.isSubscribe)?C=d(b):H=f(b.subscribersText)}else"WEBSITE"===h?((G=a4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(P=f(b.additionalFeesText)),(n=a4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=a4(b,"title","accessibility","accessibilityData","label");var Y=b.endpoint?b.endpoint.clickTrackingParams:null,
na="";if(b.metadata){var va=f(b.metadata);va&&(na=va)}return{id:"element-"+c,type:h,title:f(b.title),metadata:na,callToAction:f(b.callToAction),hV:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,yD:p,playlistLength:t,channelId:w,subscribeButton:C,subscribersText:H,isSubscribe:y,vu:m||null,c6:n,sessionData:Y?{itct:Y}:null,P$:q,cC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:h4(b.impressionUrls||[],g4),P5:h4(b.hovercardShowUrls||[],g4),clickUrls:h4(l.loggingUrls||[],g4),visualElement:g.bG(b.trackingParams),productPrice:I,additionalFeesText:P,watchEndpoint:R||null}},Ohb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:h4(a.impressionUrls||[],g4),elements:h4(a.elements||[],function(d,e){return Nhb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.bG(a.trackingParams));return c},Phb=function(a){g.IV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.S=[];this.ea=!0;this.K=0;a=a.W();this.ma=g.uS(a)||g.wS(a);this.events=new g.mL(this);g.L(this,this.events);this.events.V(this.player,g.DK("creatorendscreen"),this.onCueRangeEnter);this.events.V(this.player,g.EK("creatorendscreen"),this.onCueRangeExit);this.events.V(this.player,"resize",this.Nb);this.events.V(window,"focus",this.w9);this.load();var b=g.lf("STYLE");(g.Xe("HEAD")[0]||document.body).appendChild(b);g.ub(this,function(){g.yf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Qhb=function(a){return a.player.getVideoData().Qd?"current":a.ma?"new":"current"},i4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Rhb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Ohb(f,Qhb(a))));j4(a,f)},
urlParams:{v:c},withCredentials:!0};a.ma&&(c.urlParams.ptype="embedded");var d=b.Nx;d&&(c.postParams={ad_tracking:d});if(b=g.zQa(b))if(b=g.vn(b),b=g.ae(b))a.C=g.EC(b,c)},j4=function(a,b,c){c=void 0===c?!0:c;
a.player.lf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.S.length&&(a.S.forEach(function(l){l.dispose()}),a.S.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Shb(a);c=[];d=new g.CK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().B||(a.B=new g.U({I:"div",T:"ytp-ce-shadow"}),g.IU(a.player,a.B.element,4),a.D=new g.iH(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Thb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.IU(a.player,f.element,4);var h=new g.CK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Uhb(a,f,e)}else g.hG(new g.DD("buildEndscreenElement null",
e))}a.player.xf(c);a.Nb()}},Shb=function(a){var b=g.cG(),c=g.dG();
c&&b&&a.endscreen.visualElement&&g.lC(g.nG)(void 0,c,b,a.endscreen.visualElement)},Thb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Na:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.cC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-covering-image",Y:k4(b)},{I:"div",T:"ytp-ce-covering-shadow-top"},{I:"a",T:"ytp-ce-covering-overlay",Y:{href:l4(a,b.vu),tabindex:"-1"},X:[{I:"div",Na:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.ru(b.title||"")},Aa:b.title},{I:"div",T:b.yD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",Aa:b.videoDuration||
void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Na:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.cC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-covering-image",Y:k4(b)},{I:"div",T:"ytp-ce-covering-shadow-top"},{I:"a",T:"ytp-ce-covering-overlay",Y:{href:l4(a,b.vu),tabindex:"-1"},X:[{I:"div",Na:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.ru(b.title||"")},Aa:b.title},{I:"div",T:"ytp-ce-playlist-count",X:[{I:"div",T:"ytp-ce-playlist-icon"},
{I:"div",T:"ytp-ce-playlist-count-text",Aa:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Na:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.cC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",X:[{I:"div",
T:"ytp-ce-expanding-overlay-body",X:[{I:"div",T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"a",Na:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:l4(a,b.vu),target:"_blank",tabindex:"-1",dir:g.ru(b.title||"")},Aa:b.title},b.subscribeButton?{I:"div",T:"ytp-ce-subscribe-container",X:[{I:"div",T:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",T:"ytp-ce-channel-subscribers-text",Aa:b.subscribersText}:"",b.metadata?{I:"div",Na:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
Aa:b.metadata}:""]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:k4(b)}]};c=new g.U(c);var d=g.Ye(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.bu(d,"ytp-ce-subscribe-button");if(a.player.W().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.uW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.S.push(e)}break;case "WEBSITE":a={I:"div",Na:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.cC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",X:[{I:"div",T:"ytp-ce-expanding-overlay-body",X:[{I:"div",
T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",T:"ytp-ce-website-title",Y:{dir:g.ru(b.title||"")},Aa:b.title},{I:"div",T:"ytp-ce-website-metadata",Aa:b.metadata},{I:"a",Na:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:l4(a,b.vu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:k4(b)},{I:"div",T:"ytp-ce-expanding-icon",Y:Vhb(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",T:"ytp-ce-merchandise-price-container",
X:[{I:"div",T:"ytp-ce-merchandise-price",Aa:b.productPrice}]},b.additionalFeesText&&c.X.push({I:"div",T:"ytp-ce-merchandise-additional-fees",Aa:b.additionalFeesText})),a={I:"div",Na:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.cC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",
X:[{I:"div",T:"ytp-ce-expanding-overlay-body",X:[{I:"div",T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",T:"ytp-ce-merchandise-title",Y:{dir:g.ru(b.title||"")},Aa:b.title},c,{I:"div",T:"ytp-ce-merchandise-metadata",Aa:b.metadata},{I:"a",Na:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:l4(a,b.vu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:k4(b)},{I:"div",T:"ytp-ce-merchandise-invideo-cta-container",X:[{I:"div",T:"ytp-ce-merchandise-invideo-cta",
Aa:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.bu(c.element,"ytp-ce-placeholder");return c},k4=function(a){if(a.hV)var b=a.hV.thumbnails;
return Vhb(b?b[b.length-1].url:null)},Vhb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Uhb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.V(m,"focus",f),b.V(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.bu(b.element,"ytp-ce-force-expand"),m4(a,c.id,!0)):(g.du(b.element,"ytp-ce-force-expand"),g.du(b.element,"ytp-ce-element-hover"),m4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){Whb(a,b,c)});
b.Ta("mouseleave",function(){Xhb(a,b,c)});
a.player.W().B||b.Ta("click",function(){g.bu(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){Yhb(a,c,m)});
b.Ta("keypress",function(m){Yhb(a,c,m)});
b.Ta("focus",function(){Whb(a,b,c)});
b.Ta("blur",function(){Xhb(a,b,c)});
b.Ta("touchstart",function(){Whb(a,b,c)});
var l=g.$e("ytp-ce-expanding-overlay-hider",b.element);l&&b.V(l,"touchstart",function(m){m.stopPropagation();g.du(b.element,"ytp-ce-element-hover");g.du(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.$e("ytp-sb-subscribe",b.element));d(g.$e("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},Yhb=function(a,b,c){if(b.vu&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.au(d,"ytp-ce-element");){g.au(d,"subscribe-label")&&Zhb(a,b);
if(g.au(d,"ytp-ce-channel-subscribe"))return;d=g.zf(d)}if(!d||g.au(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Xhb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.P$)Zhb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.vn(l4(a,b.vu)),g.IH(g.ae(c),void 0,b.sessionData);else{var e=g.GS(a.player.W())||a.player.getVideoData().Qd,f=function(){var h=l4(a,b.vu),l=b.sessionData,m=b.watchEndpoint,n=g.rC(h);e&&n&&(n.v||n.list)?a.player.uo(n.v,
l,n.list,!1,void 0,m||void 0):g.dva(h,l)};
Zhb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},l4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.NS(a)+b}else return"";return b},Whb=function(a,b,c){g.au(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.bu(b.element,"ytp-ce-element-hover"):a.player.W().B?(new g.Ut(function(){g.bu(b.element,"ytp-ce-element-hover")},200)).start():g.bu(b.element,"ytp-ce-element-hover"),n4(a,c.P5),m4(a,c.id,!0))},Xhb=function(a,b,c){g.du(b.element,"ytp-ce-element-hover");
g.du(b.element,"ytp-ce-force-expand");m4(a,c.id,!1)},m4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.fu(a.j[e].element,"ytp-ce-element-shadow-show",c)},n4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||i4(a))c&&c();else{b=$hb(a,b);var e=0,f=!1,h=new g.Ut(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.UE(b[a],d)}},Zhb=function(a,b,c){n4(a,b.clickUrls,c);
(a=g.dG())&&b.c6&&g.uG(a,b.visualElement)},$hb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(aib(b[d],c));return a},aib=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},bib=function(a){return"string"===typeof a?a:""},o4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},cib=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},p4=function(a){return a.value?a.value:null},q4=function(a){if(!a)return null;
var b=g.vn(bib(a.value));b=g.ae(b);if(!b)return null;var c=o4(a.target,dib,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new cib(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},eib=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},hib=function(a){if(!a)return null;
var b=o4(a.type,fib),c=o4(a.trigger,gib);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=q4(a?a:null);return b?new eib(b,c,a):null},iib=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},jib=function(a,b){return g.Bb(a.action,b)},kib=function(a,b){this.context=a;
this.j=b},lib=function(a){return a.customMessage?r4("div","iv-card-message",a.customMessage):""},s4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",T:"iv-card-image",Y:{style:a},X:c}},mib=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(r4("li","",c.value));return{I:"ul",T:"iv-card-meta-info",X:b}},r4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.ru(c);return{I:a,Y:b,Aa:c}},nib=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.mC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.mC+");");c.dir=g.ru(a.customMessage);var d=[{I:"span",Aa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",T:"iv-card-link-icon"}));return{I:"div",Na:b,Y:c,X:d}},t4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Zi.click,5)}},oib=function(a,b){this.merchant=a;
this.price=b},pib=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},qib=function(a,b){return b?b:pib(a)?"current":"new"},u4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.zb=!1;this.eb=new Map;this.gb=new Map;this.context.J.addEventListener(g.DK("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.EK("annotations_module"),function(d){(d=c.gb.get(d))&&d.apply(c)})},v4=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.BK(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.zb=!1});
a.context.j.Ta(b,"touchmove",function(){a.zb=!0})},rib=function(a){var b;
return(null==(b=g.T(a,g.WG))?0:b.url)?g.T(a,g.WG).url:(a=g.T(a,g.DT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},w4=function(a,b,c){return{FW:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
SZ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
bK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},sib=function(a,b,c){u4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Pa=this.Mb=this.C=this.isInitialized=!1;this.cards=[];this.Bb=this.ma=this.Oa=this.G=this.Ya=this.j=null;this.qa=[];this.va=this.S=this.pg=this.Ia=null;this.K=0;this.Fa=new g.Ut(function(){},c.Z.Oi?4E3:3E3);
g.L(this,this.Fa);this.tb=new g.Ut(function(){});
g.L(this,this.tb);this.Ca=new kib(c,function(e,f,h,l,m,n){v4(d,e,f,h,l,m,n)});
this.ea=new g.U({I:"div",T:"iv-drawer",Y:{id:"iv-drawer"},X:[{I:"div",T:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{I:"span",T:"iv-drawer-header-text"},{I:"button",Na:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"\u0421\u0445\u043e\u0432\u0430\u0442\u0438 \u043a\u0430\u0440\u0442\u043a\u0438",tabindex:"0"}}]},{I:"div",T:"iv-drawer-content"}]});g.L(this,this.ea);this.D=this.ea.element;this.kb=new g.iH(this.ea,330);g.L(this,this.kb);this.Ub=g.$e("iv-drawer-header-text",this.D);this.B=
g.$e("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Mb&&x4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Mb=d.C)&&y4(d)});
this.Va=new g.mL(this);g.L(this,this.Va);this.J.addEventListener("videodatachange",this.ot.bind(this))},tib=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){x4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){y4(a)});
var c=b.headerText;g.Bf(a.Ub,c);a.ma&&a.ma.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.bG(b.trackingParams);a.S=g.bG(b.closeTrackingParams);a.pg=g.bG(b.iconTrackingParams)},uib=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.W().experiments.qb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.KG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Zi:{},Qo:null,zl:e.trackingParams?g.bG(e.trackingParams):null,pg:f&&f.trackingParams?g.bG(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
mC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};z4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.KG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:A4(a,c,b,f),sponsored:!1,Zi:w4(f,e,f.command),Qo:f.trackingParams?g.bG(f.trackingParams):null,zl:e.trackingParams?g.bG(e.trackingParams):null,pg:l&&l.trackingParams?g.bG(l.trackingParams):null,imageUrl:B4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.KG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,mC:null,title:f.title?g.KG(f.title):"",customMessage:f.callToAction?g.KG(f.callToAction):"",url:g.T(f.command,g.WG).url?q4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.T(f.command,g.WG).url}):null,onClickCommand:null};z4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.KG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Zi:w4(e,f,e.endpoint),Qo:e.trackingParams?g.bG(e.trackingParams):null,zl:f.trackingParams?g.bG(f.trackingParams):null,pg:l&&l.trackingParams?g.bG(l.trackingParams):null,channelId:g.T(e.endpoint,g.fV).browseId,customMessage:e.customText?g.KG(e.customText):null,QY:B4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.KG(e.channelName):"",metaInfo:[e.subscriberCountText?g.KG(e.subscriberCountText):""],url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.T(e.endpoint,g.fV).canonicalBaseUrl?g.T(e.endpoint,g.fV).canonicalBaseUrl:"/channel/"+g.T(e.endpoint,g.fV).browseId}),onClickCommand:null};z4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.KG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Zi:w4(e,f,e.action),Qo:e.trackingParams?g.bG(e.trackingParams):null,zl:f.trackingParams?g.bG(f.trackingParams):null,pg:l&&l.trackingParams?g.bG(l.trackingParams):null,rF:B4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.KG(e.customMessage):null,playlistVideoCount:g.KG(e.playlistVideoCount),title:e.playlistTitle?g.KG(e.playlistTitle):"",metaInfo:[e.channelName?g.KG(e.channelName):
"",e.videoCountText?g.KG(e.videoCountText):""],url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:rib(e.action)}),onClickCommand:null};z4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.KG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Zi:w4(e,f,e.action),Qo:e.trackingParams?g.bG(e.trackingParams):null,zl:f.trackingParams?g.bG(f.trackingParams):null,pg:l&&l.trackingParams?g.bG(l.trackingParams):null,rF:B4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.KG(e.lengthString):null,customMessage:e.customMessage?g.KG(e.customMessage):null,title:e.videoTitle?g.KG(e.videoTitle):"",metaInfo:[e.channelName?g.KG(e.channelName):
"",e.viewCountText?g.KG(e.viewCountText):""],isLiveNow:!!e.badge,url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:rib(e.action)}),onClickCommand:null};z4(a,b)}}}}}a.K++},B4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},A4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},wib=function(a,b){if(b=vib(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.gg.id),g.yf(b.fM),g.Fb(a.cards,b),a.oG(),C4(a)},x4=function(a,b,c){if(!a.C){a.kb.show();
a.Ya=new g.Ut(function(){g.bu(a.context.J.getRootNode(),g.jZ.IV_DRAWER_OPEN)},0);
a.Ya.start();a.Va.V(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.dG();d&&a.Ia&&a.S&&g.sG(d,[a.Ia,a.S]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.oX||(f.oX=!0,xib(a.context.logger,f.gg.Zi.FW,b)),d&&g.sG(d,[f.gg.Qo]);$3(a.J);c&&(a.G=new g.Ut(function(){a.Oa=a.ma;a.Bb.focus()},330),a.G.start())}},y4=function(a){a.C&&(a.kb.hide(),g.sD(a.Va),g.du(a.context.J.getRootNode(),g.jZ.IV_DRAWER_OPEN),a.C=!1,$3(a.J),a.G&&a.G.stop(),a.G=new g.Ut(function(){a.Oa&&(a.Oa.focus(),a.Oa=null)},330),a.G.start())},zib=function(a){g.cu(a.Eb(),
[g.jZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.IU(a.J,a.D,5);yib(a);a.ma=g.$e("ytp-cards-button",a.J.getRootNode());a.Bb=g.$e("iv-drawer-close-button",a.D);a.isInitialized=!0},yib=function(a){var b=g.$e("iv-drawer-close-button",a.D);
a.context.j.Ta(b,"click",a.U3,a);a.context.j.Ta(a.B,"touchend",function(){a.Fa.start()});
a.context.j.Ta(a.B,"scroll",a.q4,a);a.context.B.subscribe("onHideControls",function(){a.Pa=!0});
a.context.B.subscribe("onShowControls",function(){a.Pa=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Pa=g.au(a.J.getRootNode(),"ytp-autohide")});
a.qa.push(g.lF("iv-button-shown",a.q6,a));a.qa.push(g.lF("iv-button-hidden",a.p6,a));a.qa.push(g.lF("iv-teaser-shown",a.A0,a));a.qa.push(g.lF("iv-teaser-hidden",a.r6,a));a.qa.push(g.lF("iv-teaser-clicked",a.z0,a))},Aib=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.T(b.onClickCommand,g.Xdb))?void 0:c.targetId)?(a.va=b,!0):!1},Bib=function(a,b){a.va=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.YOa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.T(h[0],g.wXa))?void 0:d.timeRangeStartMillis)||0,a.va=null,!0}return!1},z4=function(a,b){if(!Aib(a,b)||Bib(a,b)){var c=Cib(a,b);
if(c){var d={gg:b,fM:c.element,oX:!1};if(!b.onClickCommand){a.isInitialized||zib(a);wib(a,b.id);var e=Dib(a,d);g.Ob(a.cards,e,0,d);c.Ga(a.B,e);a.oG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,C4(a),Eib(a,d),x4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Fib(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Fib(a,d)}),C4(a))}}},Cib=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",T:"iv-card-image-text",Aa:b.displayDomain}:void 0;var d=nib(b);c={I:"div",Na:["iv-card"],X:[{I:"a",T:"iv-click-target",Y:{href:b.url?p4(b.url)||"":""},X:[s4(b.imageUrl,c),{I:"div",T:"iv-card-content",X:[r4("h2",void 0,b.title),d]}]}]};c=new g.U(c);t4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Na:["iv-card","iv-card-channel"],X:[{I:"a",Na:["iv-click-target"],Y:{href:p4(b.url)||"","data-ytid":b.channelId},X:[s4(b.QY),{I:"div",
T:"iv-card-content",X:[lib(b),{I:"h2",T:"iv-card-primary-link",Aa:b.title},mib(b)]}]}]};c=new g.U(c);t4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Na:["iv-card","iv-card-playlist"],X:[{I:"a",T:"iv-click-target",Y:{href:p4(b.url)||""},X:[s4(b.rF,{I:"div",T:"iv-card-image-overlay",X:[{I:"span",T:"iv-card-playlist-video-count",Aa:b.playlistVideoCount}]}),{I:"div",T:"iv-card-content",X:[lib(b),r4("h2","iv-card-primary-link",b.title),mib(b)]}]}]};c=new g.U(c);
t4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=nib(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",T:"iv-card-offer-price",Aa:f.price}),f.merchant&&e.push({I:"div",T:"iv-card-offer-merchant",Aa:f.merchant}),f={I:"div",X:e});e=b.url?p4(b.url)||"":"";c={I:"div",Na:c,Y:{tabindex:"0"},X:[{I:"a",Na:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",T:"iv-card-content",X:[b.sponsored?{I:"div",T:"iv-card-sponsored",X:["\u0420\u0435\u043a\u043b\u0430\u043c\u0430",{I:"div",T:"iv-ad-info-container",X:[{I:"div",T:"iv-ad-info",Aa:"{{adInfo}}"},{I:"div",T:"iv-ad-info-icon-container",X:[{I:"div",T:"iv-ad-info-icon"},{I:"div",T:"iv-ad-info-callout"}]}]}]}:"",{I:"a",T:"iv-click-target",Y:{href:e},X:[r4("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.lf("span");g.Bf(d,"\u0412\u0438 \u0431\u0430\u0447\u0438\u0442\u0435 \u0446\u0435\u0439 \u043f\u0440\u043e\u0434\u0443\u043a\u0442, \u043e\u0441\u043a\u0456\u043b\u044c\u043a\u0438 \u043c\u0438 \u0432\u0432\u0430\u0436\u0430\u0454\u043c\u043e, \u0449\u043e \u0432\u0456\u043d \u043f\u043e\u0432\u2019\u044f\u0437\u0430\u043d\u0438\u0439 \u0456\u0437 \u0432\u0456\u0434\u0435\u043e. Google \u043c\u043e\u0436\u0435 \u043e\u0442\u0440\u0438\u043c\u0443\u0432\u0430\u0442\u0438 \u0434\u043e\u0445\u0456\u0434 \u0432\u0456\u0434 \u0440\u043e\u0437\u043c\u0456\u0449\u0435\u043d\u043d\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u0438 \u0446\u044c\u043e\u0433\u043e \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u044f.");
c.pe(d,"adInfo");t4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",T:"iv-card-video-duration",Aa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Na:["yt-badge","yt-badge-live"],Aa:"\u0423 \u041f\u0420\u042f\u041c\u041e\u041c\u0423 \u0415\u0424\u0406\u0420\u0406"}:null;e={I:"div",Na:["iv-card","iv-card-video"],X:[{I:"a",T:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:p4(c))||""},X:[s4(b.rF,d),{I:"div",T:"iv-card-content",X:[lib(b),r4("h2",
"iv-card-primary-link",b.title),mib(b),f]}]}]};c=new g.U(e);t4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;default:return null}return b},Dib=function(a,b){if(0===a.cards.length)return 0;
a=g.Cb(a.cards,function(c){return b.gg.startMs>c.gg.startMs||b.gg.startMs===c.gg.startMs&&b.gg.timestamp>=c.gg.timestamp?!0:!1});
return-1===a?0:a+1},Gib=function(a){if(a.j)return"productListing"===a.j.gg.type;
if(a.J.N("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Vp(a.cards,function(c){return"productListing"===c.gg.type})}return g.Vp(a.cards,function(c){return"productListing"===c.gg.type})},C4=function(a){g.fu(a.J.getRootNode(),"ytp-cards-shopping-active",Gib(a))},Fib=function(a,b){if(!g.au(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.dG(),d=a.j?a.j.gg.pg:a.pg;
c&&d&&g.tG(c,[d]);a.j=b;C4(a)}(c=a.isInitialized&&"none"==a.Eb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.gg.teaserDurationMs&&a.J.QA(!0,{teaserText:b.gg.teaserText,durationMs:b.gg.teaserDurationMs,onClickCommand:b.gg.onClickCommand});a.tb.isActive()||((!a.C||!a.Fa.isActive()&&a.Pa)&&Eib(a,b),a.tb.start(910+b.gg.teaserDurationMs))}},Eib=function(a,b){a.ea.Ib?(b=new e4([0,
a.B.scrollTop],[0,b.fM.offsetTop],600,Lhb),a.context.C.Ta(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ta(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.GG(a.ea,!0),a.B.scrollTop=b.fM.offsetTop,g.GG(a.ea,!1))},D4=function(a){return a.j&&a.j.gg?a.j.gg:a.cards[0]&&a.cards[0].gg?a.cards[0].gg:null},vib=function(a,b){return g.Bb(a.cards,function(c){return c.gg.id===b})},E4=function(a,b,c){u4.call(this,a,b);
this.annotation=c;this.isActive=!1},Hib=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},F4=function(a,b,c){E4.call(this,a,b,c);
this.B=null;this.S=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Iib=function(a,b){var c=void 0===c?0:c;
var d=Chb(b).width;g.wr(b,d);c=new Jhb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Khb);g.L(a,c);a.context.C.Ta(c,"begin",function(){g.Cr(b,!0)});
c.play()},Lib=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Na:["iv-branding-context-name"],Aa:b.channel_name}),d=a.createElement({I:"div",Na:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.uW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Ga(d));var f=a.createElement({I:"div",Na:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Na:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Cr(h,!1);var l=a.createElement({I:"div",Na:["branding-context-container-outer"]});l.appendChild(h);g.qr(l,"right",b.image_width+"px");g.nf(a.Eb(),l);a.C=new g.Ut(function(){Jib(a,h,l)},500);
g.L(a,a.C);a.context.j.Ta(a.Eb(),"mouseover",function(){Kib(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Eb(),"mouseout",function(){a.C.start()})}},Kib=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Br(b);a.j||(b.style.width=g.vr(f.width,!0),c.style.width=g.vr(f.width,!0));g.qr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.qr(d,"right","1px");a.D=!0;g.Cr(b,!0);a.G=new g.Ut(function(){g.bu(this.Eb(),"iv-branding-active")},0,a);
a.G.start()}},Jib=function(a,b,c){g.du(a.Eb(),"iv-branding-active");
a.K=new g.Ut(function(){g.Cr(b,!1);a.j||(c.style.width=g.vr(0,!0))},250);
a.K.start();a.D=!1},Mib=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Z=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Nib=function(a,b,c){E4.call(this,a,b,c);
var d=this;this.ma=this.isCollapsed=this.ea=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.S=this.createElement({I:"div",Na:["iv-promo-contents"]});this.G=new g.Ut(function(){d.j.setAttribute("aria-hidden","true");g.Cr(d.C,!1);g.Cr(d.B,!0)},700,this);
g.L(this,this.G)},Qib=function(a,b,c){c.stopPropagation();
Oib(a);Pib(a,b);a.j.focus()},Rib=function(a){a.isCollapsed||a.ma||a.D||(g.bu(a.Eb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Oib=function(a){a.G.stop();
a.isCollapsed&&(g.eu(a.Eb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Cr(a.B,!1),g.Cr(a.C,!0))},Pib=function(a,b){a.D||(a.D=g.hg(function(){Sib(this);
Rib(this)},b,a))},Sib=function(a){a.D&&(g.Qa.clearTimeout(a.D),a.D=null)},Tib=function(a){this.J=a},xib=function(a,b,c){b&&(c?G4(a,b.map(function(d){return g.Jt(d,c)})):G4(a,b))},G4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.UE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Uib=function(a){g.IV.call(this,a);
var b=this;this.ea=this.S=!1;this.loadNumber=0;this.K={};this.logger=new Tib(this.player);this.D=new g.mL(this);this.G=this.hx=null;this.events=new g.mL(this);this.wh=this.ma=this.j=null;this.qa=[];g.L(this,this.D);this.D.V(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.D.V(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.D.V(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.D.V(this.player,"resize",function(d){b.ra("resize",d)});
this.D.V(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.B0,this);this.subscribe("resize",this.NI,this);this.player.W().Oa.subscribe("vast_info_card_add",this.wY,this);g.L(this,this.events);this.va=this.createElement({I:"div",T:"video-custom-annotations"});this.B=new g.U({I:"div",Na:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.IU(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Na:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",T:"video-annotations"});
a.appendChild(this.va);this.C.element.appendChild(a);this.fu()&&this.load();var c=this.createElement({I:"style"});(g.Xe("HEAD")[0]||document.body).appendChild(c);g.ub(this,function(){g.yf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Vib=function(a){a=a.createElement({I:"div",
Na:["annotation","annotation-type-custom"]});g.Cr(a,!1);return a},Wib=function(a,b){b=!b.isCued()&&!g.oH(b,1024);
g.GG(a.B,b);g.GG(a.C,b)},Xib=function(a,b,c){a.S=!0;
a.G=g.EC(b,c)},Yib=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Xa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Yib(a,e))}return c},bjb=function(a){var b=a.player.getVideoData();
if(b.Ya){var c=a.player.W().Oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.yC(h)&&h.responseXML?h.responseXML:null)&&Zib(a,h)}};
g.LD()&&(d.onFinish=$ib(a,d.onFinish));d.postParams={ic_only:"1"};ajb(d,c);a.S=!0;g.EC(b.Ya,d)}}},ajb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.tG&&(a.postParams.ic_coll=b.tG);b.gM&&(a.postParams.ic_xml=b.gM);b.fK&&(a.postParams.ic_track=b.fK)},cjb=function(a){var b=new g.U({I:"div"});
g.Cr(b.element,!1);var c=new sib(a.player,b.element,H4(a));g.L(c,b);b.Ga(a.B.element);c.hF();return c},ejb=function(a,b){var c,d;
if(b=null==(c=b.Kd)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ea=!0,djb(a,b),b.headerText&&a.wh&&(c=g.KG(b.headerText),a.wh.setAttribute("title",c))},H4=function(a){if(!a.ma){var b=new Mhb(a);
g.L(a,b);var c=new g.lo(a);g.L(a,c);a.ma=new Mib(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.Oi)}return a.ma},Zib=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.dG();if(e){var f=g.cG();f&&g.lC(g.pta)(void 0,e,f,[g.bG(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Yib(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=o4(f.type,fjb),p=o4(f.style,gjb),q=bib(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=hib;if(null==t)var w=null;else if(g.Wa(t)){l=[];for(var y=g.u(t),C=y.next();!C.done;C=y.next()){var H=f(C.value);
H&&l.push(H)}w=l}else{var G=f(t);w=G?[G]:[]}e=m&&n?new iib(m,n,p,w,r):null}else e=null}catch(va){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=Vib(f),P=null;switch(l.type){case "branding":if(f.player.W().Ud)break;f.B.element.appendChild(I);P=new F4(I,H4(f),l);break;case "promotion":g.IU(f.player,I,4),P=new Nib(I,H4(f),l)}P&&P.hF();if(f=P)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=cjb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var R=e&&e.data&&e.data.card_type;
f=e.data;if(R)switch(l=f.tracking||{},l={FW:l.impression,click:l.click,close:l.close,SZ:l.teaser_impression,bK:l.teaser_click},I=f.tracking_params||{},P=null,R){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Qo:I.card?g.bG(I.card):null,zl:I.teaser?g.bG(I.teaser):null,pg:I.icon?g.bG(I.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,QY:f.image_url,title:f.title,metaInfo:f.meta_info,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Qo:I.card?g.bG(I.card):null,zl:I.teaser?
g.bG(I.teaser):null,pg:I.icon?g.bG(I.icon):null,rF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "productListing":f.signin_url&&(P=q4({target:"current",value:f.signin_url}));R=[];for(var Y=f.offers||[],na=0;na<Y.length;na++)R.push(new oib(g.Je(Y[na].merchant),g.Je(Y[na].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Qo:I.card?g.bG(I.card):null,zl:I.teaser?g.bG(I.teaser):null,pg:I.icon?g.bG(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,mC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Xfb:P,Wfb:f.signin_title?f.signin_title:void 0,Vfb:f.signin_message?f.signin_message:void 0,offers:R,onClickCommand:null};z4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Qo:I.card?g.bG(I.card):
null,zl:I.teaser?g.bG(I.teaser):null,pg:I.icon?g.bG(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,mC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Zi:l,Qo:I.card?g.bG(I.card):null,zl:I.teaser?g.bG(I.teaser):null,pg:I.icon?g.bG(I.icon):null,rF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},z4(c,e)}}else tib(a.j,e);c=!0}}c&&
($3(a.player),a.NI())},djb=function(a,b){var c=!1;
a.j||(a.j=cjb(a),g.L(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(uib(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.WT(f)||(c=a.j,d=b.headerText?g.KG(b.headerText):"",g.Bf(c.Ub,d),c.ma&&c.ma.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.bG(b.trackingParams):null,c.S=b.closeButton.infoCardIconRenderer.trackingParams?g.bG(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.pg=b.icon.infoCardIconRenderer.trackingParams?g.bG(b.icon.infoCardIconRenderer.trackingParams):null,a.NI());$3(a.player)}},hjb=function(a,b,c,d,e){if(!a.player.W().Ud){var f=[];
b.navigationEndpoint&&g.T(b.navigationEndpoint,g.fV)&&g.T(b.navigationEndpoint,g.fV).browseId&&f.push(new eib("openUrl","click",new cib("/channel/"+g.T(b.navigationEndpoint,g.fV).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.T(b.subscribeButton,
g.PT)){d.channel_id=g.T(b.subscribeButton,g.PT).channelId;var l;b=g.T(b.subscribeButton,g.PT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.KG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.KG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.KG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.KG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.T(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.S2))?void 0:m.url)||"";l={subscribeText:g.KG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.KG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new iib(c,"branding","branding",f,d);l=Vib(a);a.B.element.appendChild(l);f=new F4(l,H4(a),f);f.hF();g.L(f,f);a.K[c]=f}},$ib=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.isDisposed()||a.qa.push(g.Mt.Ii(function(){b.apply(null,g.qa(c))}))}},ijb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.AU.prototype.QA=g.ea(19,function(a,b){var c=g.ZV(this.Hb());c&&c.QA(a,b)});
var b4={},c4=null;g.gb(e4,g.nu);g.k=e4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;d4(this);this.startTime=a=g.eb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.DI();this.gm("play");this.isPaused()&&this.gm("resume");this.j=1;var b=g.ab(this);b in b4||(b4[b]=this);Fhb();Ghb(this,a);return!0};
g.k.stop=function(a){d4(this);this.j=0;a&&(this.progress=1);Hhb(this,this.progress);this.gm("stop");this.ir()};
g.k.pause=function(){this.isPlaying()&&(d4(this),this.j=-1,this.gm("pause"))};
g.k.Ba=function(){0==this.j||this.stop(!1);this.gm("destroy");e4.Qf.Ba.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.AK=function(){this.gm("animate")};
g.k.gm=function(a){this.dispatchEvent(new Ihb(a,this))};
g.gb(Ihb,g.xb);g.gb(f4,e4);f4.prototype.C=function(){};
f4.prototype.AK=function(){this.C();f4.Qf.AK.call(this)};
f4.prototype.ir=function(){this.C();f4.Qf.ir.call(this)};
f4.prototype.DI=function(){this.C();f4.Qf.DI.call(this)};
g.gb(Jhb,f4);Jhb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(Mhb,g.J);g.k=Mhb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.cb)(c,d||this.B);a=g.mD(a,b,c);this.j.push(a);return a};
g.k.dI=function(a,b,c,d){c=(0,g.cb)(c,d||this.B);a=Dhb(a,b,c);this.j.push(a);return a};
g.k.Qc=function(a){g.nD(a);g.Fb(this.j,a)};
g.k.Of=function(){g.nD(this.j);this.j.length=0};
g.k.Ba=function(){this.Of();g.J.prototype.Ba.call(this)};g.v(Phb,g.IV);g.k=Phb.prototype;g.k.load=function(){g.IV.prototype.load.call(this);if(!i4(this)){var a=g.AQa(this.player.getVideoData());a?(a=Ohb(a,Qhb(this)),j4(this,a,!1)):Rhb(this)}};
g.k.unload=function(){j4(this,null);this.C&&(this.C.abort(),this.C=null);g.IV.prototype.unload.call(this)};
g.k.Ih=function(a,b){return i4(this)?"loadCustomEndscreenRenderer"===a?(a=Ohb(b,"new"),j4(this,a),!0):null:null};
g.k.getOptions=function(){return i4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Nb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<jjb.length;f++){var h=Math.abs(b.width-jjb[f]);if(-1===e||d>=h)e=f,d=h}d=kjb[e];this.B&&g.qr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ar(e.element,m,f);g.wr(e.element,n,p);g.eu(e.element,ljb);256<m||256<f?g.bu(e.element,"ytp-ce-large-round"):96<m||96<f?g.bu(e.element,"ytp-ce-medium-round"):g.bu(e.element,"ytp-ce-small-round");g.eu(e.element,mjb);m=h.left+h.width/2;h=h.top+l/2;g.bu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.eu(e.element,kjb);g.bu(e.element,d);(e=g.Ye(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.qr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())n4(this,this.endscreen.impressionUrls),(a=g.dG())&&this.endscreen.visualElement&&g.rG(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.bu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.bu(b,"ytp-ce-shown");n4(this,c.impressionUrls);(b=g.dG())&&g.rG(b,c.visualElement);this.player.W().K&&this.player.Ua("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.du(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.du(b,"ytp-ce-shown");this.player.W().K&&this.player.Ua("endscreenelementhidden",a)}};
g.k.w9=function(a){var b=this;a.target===window&&(new g.Ut(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.eu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var jjb=[346,426,470,506,570,640,853,1280,1920],kjb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),mjb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],ljb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var dib={Vpa:"current",HPa:"new"};var fib={CLOSE:"close",iTa:"openUrl",SUBSCRIBE:"subscribe"},gib={xoa:"click",CLOSE:"close",kBa:"hidden",gYa:"rollOut",hYa:"rollOver",NZa:"shown"};iib.prototype.hf=function(){var a=jib(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var gjb={uja:"anchored",W_:"branding",CHANNEL:"channel",Lpa:"cta",nBa:"highlightText",oFa:"label",PLAYLIST:"playlist",GVa:"popup",K1a:"speech",SUBSCRIBE:"subscribe",U4a:"title",VIDEO:"video",fbb:"website"},fjb={W_:"branding",rma:"card",Vra:"drawer",mBa:"highlight",pLa:"marker",bXa:"promotion",TEXT:"text",Hcb:"widget"};g.v(u4,g.J);g.k=u4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.CK(a,b,{id:c,namespace:"annotations_module"});d&&this.eb.set(a,d);e&&this.gb.set(a,e);this.context.J.xf([a])};
g.k.hF=function(){this.context.B.subscribe("resize",this.oG,this)};
g.k.Eb=function(){return this.element};
g.k.BK=function(a,b,c,d,e,f){if(this.zb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.yf(this.Eb())};
g.k.oG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=p4(a);if(f){var h=qib(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Qd||!1,n=g.rC(f||"");m&&n&&(n.v||n.list)?e.context.J.uo(n.v,b,n.list,!1):g.IH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);G4(this.context.logger,c,l,d);pib(f)||(c=g.dG(),d=b.itct,c&&d&&g.uG(c,g.bG(d)))}};
g.k.Ba=function(){this.eb.clear();this.gb.clear();g.J.prototype.Ba.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.v(sib,u4);g.k=sib.prototype;g.k.ot=function(){this.va&&z4(this,this.va)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Br(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.oG=function(){var a=this.isAvailable();g.Cr(this.Eb(),a);g.fu(this.context.J.getRootNode(),g.jZ.IV_DRAWER_ENABLED,a);$3(this.J)};
g.k.destroy=function(){this.J.QA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.mF(this.qa);g.sD(this.Va);this.Ya&&this.Ya.dispose();this.G&&this.G.dispose();u4.prototype.destroy.call(this)};
g.k.U3=function(){if(this.C){G4(this.context.logger,D4(this).Zi.close);var a=g.dG();a&&this.S&&g.uG(a,this.S);y4(this)}};
g.k.q4=function(){g.fu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.q6=function(){var a=g.dG(),b=D4(this);b=b?b.pg:this.pg;a&&b&&g.sG(a,[b])};
g.k.p6=function(){var a=g.dG(),b=D4(this);b=b?b.pg:this.pg;a&&b&&g.tG(a,[b])};
g.k.A0=function(){var a=D4(this);G4(this.context.logger,a.Zi.SZ);var b=g.dG();b&&a&&g.sG(b,[a.zl,a.pg])};
g.k.r6=function(){var a=g.dG(),b=D4(this);a&&b&&g.tG(a,[b.zl])};
g.k.z0=function(a){var b=D4(this),c=g.dG();this.j?a?(a=this.context.logger,G4(a,b.Zi.bK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.zl&&g.uG(c,b.zl)):(a=this.context.logger,G4(a,b.Zi.bK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.pg&&g.uG(c,b.pg)):(a=this.context.logger,G4(a,b.Zi.bK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.pg&&g.uG(c,this.pg))};g.v(E4,u4);E4.prototype.hF=function(){u4.prototype.hF.call(this);Hib(this)};
E4.prototype.show=function(){u4.prototype.show.call(this);var a=g.dG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.sG(a,[g.bG(b.itct)])};
E4.prototype.hide=function(){u4.prototype.hide.call(this);var a=g.dG(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.tG(a,[g.bG(b.itct)])};g.v(F4,E4);
F4.prototype.GA=function(){g.bu(this.Eb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Na:["branding-img","iv-click-target"],Y:{"aria-label":"\u0412\u043e\u0434\u044f\u043d\u0438\u0439 \u0437\u043d\u0430\u043a \u043a\u0430\u043d\u0430\u043b\u0443",src:a.image_url,width:a.image_width,height:a.image_height}});g.Cr(this.B,!1);var b=this.createElement({I:"button",Na:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Eb().appendChild(b);var c=this.annotation.hf();
c&&v4(this,b,c,this.annotation.id,a.session_data);Lib(this,a)};
F4.prototype.show=function(){if(!this.isActive&&(E4.prototype.show.call(this),this.S||(this.GA(),this.S=!0),g.Cr(this.Eb(),!0),this.isActive=!0,this.B)){try{Iib(this,this.B)}catch(a){}g.bu(this.context.J.getRootNode(),"ytp-branding-shown")}};
F4.prototype.hide=function(){this.isActive&&(E4.prototype.hide.call(this),g.Cr(this.Eb(),!1),this.isActive=!1,g.du(this.context.J.getRootNode(),"ytp-branding-shown"))};
F4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);E4.prototype.destroy.call(this)};g.v(Nib,E4);g.k=Nib.prototype;
g.k.GA=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Eb().setAttribute("aria-hidden","true");this.Eb().setAttribute("aria-label","\u0420\u0435\u043a\u043b\u0430\u043c\u0430");this.Eb().tabIndex=0;var e=this.annotation.hf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Na:["iv-promo-img","iv-click-target"]});
f=this.createElement({I:"img",Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",T:"iv-promo-video-duration",Aa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",T:"iv-promo-playlist-length",Aa:b.playlist_length.toString()}),h.appendChild(f));e&&v4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",T:"iv-promo-txt"}),g.wn(f,p4(e)),this.j=f):this.j=this.createElement({I:"div",
T:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=this.createElement({I:"p",X:[{I:"strong",Aa:b.text_line_1}]});var m=this.createElement({I:"p",X:[{I:"span",T:"iv-promo-link",Aa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Na:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Na:["iv-button","iv-promo-button"],X:[{I:"span",T:"iv-button-content",Aa:f}]});var p=this.createElement({I:"div",
T:"iv-promo-button-container"});p.appendChild(f);e&&v4(this,this.Eb(),e,this.annotation.id,b.session_data,void 0,c)}g.bu(this.j,"iv-click-target");e&&v4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",X:[{I:"span",Aa:b.text_line_1}]}),m=this.createElement({I:"p",X:[{I:"strong",Aa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Na:["yt-badge","iv-promo-badge-live"],Aa:"\u0423 \u041f\u0420\u042f\u041c\u041e\u041c\u0423 \u0415\u0424\u0406\u0420\u0406"})),
g.bu(this.j,"iv-click-target"),e&&v4(this,this.j,e,this.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.S.appendChild(this.j);p&&this.S.appendChild(p);c=this.createElement({I:"div",T:"iv-promo-actions"});this.B=this.createElement({I:"button",Na:["iv-promo-expand","ytp-button"]});this.B.title="\u0420\u043e\u0437\u0433\u043e\u0440\u043d\u0443\u0442\u0438";this.context.j.Ta(this.B,"click",function(q){Qib(a,5E3,q)});
c.appendChild(this.B);g.Cr(this.B,!1);this.context.j.Ta(this.Eb(),"mouseover",this.q5,this);this.context.j.Ta(this.Eb(),"mouseout",this.p5,this);this.context.j.Ta(this.Eb(),"touchend",function(q){Qib(a,5E3,q)});
this.C=this.createElement({I:"button",Na:["iv-promo-close","ytp-button"]});this.C.title="\u0417\u0430\u043a\u0440\u0438\u0442\u0438";this.context.j.Ta(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.l5:this.k5,this);c.appendChild(this.C);g.cu(this.Eb(),d);h&&(g.nf(this.Eb(),h),n&&h.appendChild(n));g.nf(this.Eb(),this.S);g.nf(this.Eb(),c)};
g.k.show=function(){this.isActive||(E4.prototype.show.call(this),this.ea||(this.GA(),this.ea=!0),g.Cr(this.Eb(),!0),g.hg(function(){g.du(this.Eb(),"iv-promo-inactive")},100,this),this.Eb().removeAttribute("aria-hidden"),this.isActive=!0,Sib(this),Oib(this),Pib(this,this.K))};
g.k.hide=function(){this.isActive&&(g.bu(this.Eb(),"iv-promo-inactive"),this.isActive=!1,this.Eb().setAttribute("aria-hidden","true"))};
g.k.BK=function(a,b,c,d,e,f){return this.isCollapsed?!1:E4.prototype.BK.call(this,a,b,c,d,e,f)};
g.k.q5=function(a){this.ma=!0;Qib(this,500,a)};
g.k.p5=function(){this.ma=!1;Rib(this)};
g.k.k5=function(a){a.stopPropagation();this.hide()};
g.k.l5=function(a){a.stopPropagation();Sib(this);this.isCollapsed=!0;g.bu(this.Eb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();E4.prototype.destroy.call(this)};g.v(Uib,g.IV);g.k=Uib.prototype;g.k.Ih=function(a,b){if(!ijb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.Gbb(b))&&Zib(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(wib(this.j,b),$3(this.player)),!0}return null};
g.k.getOptions=function(){return ijb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.fu=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Qd&&a.qa||g.uU(this.player.app)?!1:1===c&&!b.eU||a.Oa.get(b.videoId)||g.XT(b)||g.BQa(b)?!0:!1};
g.k.NI=function(){if(this.C){var a=this.player.rb().getVideoContentRect(!0);g.Ar(this.C.element,a.width,a.height);g.wr(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Mk();a=this.j;b=b.width;g.fu(a.D,"iv-drawer-small",426>=b);g.fu(a.D,"iv-drawer-big",1280<=b)}};
g.k.B0=function(a){Wib(this,a.state);g.oH(a.state,2)&&(this.Bk()&&this.Po()&&2!==this.player.getPresentingPlayerType()&&this.RA(!1),this.QA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.yC(h)&&h.responseXML?h.responseXML:null)&&(Zib(b,h),g.bu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.IV.prototype.load.call(this);Wib(this,this.player.Tb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.LD()&&(a=$ib(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Oa.get(d);f&&ajb(e,f);f=f&&(f.gM||f.tG);if(!c.mx||f)c.Ya?Xib(this,c.Ya,e):(this.hx=function(){if(!b.S)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.WT(h))&&!b.ea&&ejb(b,h)},this.player.addEventListener("videodatachange",this.hx));
g.IU(this.player,this.C.element,4);this.NI();(f=g.XT(c))&&djb(this,f);(f=g.BQa(c))&&f.featuredChannel&&hjb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.wh=g.$e("ytp-cards-button",this.player.getRootNode());g.WT(c)&&ejb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ya&&Xib(this,b.Ya,a)};
g.k.unload=function(){this.player.lf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.ma=null;this.j&&(this.j.destroy(),this.j=null,$3(this.player));this.S=!1;this.G&&(this.G.abort(),this.G=null);this.ea=!1;this.K={};this.B.hide();g.IV.prototype.unload.call(this);this.C.detach();this.hx&&(this.player.removeEventListener("videodatachange",this.hx),this.hx=null)};
g.k.wY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?bjb(this):this.load())};
g.k.Bk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.Po=function(){return!!this.j&&this.j.C};
g.k.RA=function(a,b,c){b=void 0===b?!1:b;this.Bk();this.j&&(a?c?x4(this.j,c,b):x4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):y4(this.j))};
g.k.QA=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.Ba=function(){this.player.W().Oa.unsubscribe("vast_info_card_add",this.wY,this);g.du(this.player.getRootNode(),g.jZ.IV_DRAWER_OPEN);for(var a=this.qa,b=g.Mt,c=0,d=a.length;c<d;c++)b.Jj(a[c]);this.qa.length=0;g.IV.prototype.Ba.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.HV("annotations_module",Uib);g.HV("creatorendscreen",Phb);})(_yt_player);
