(function(g){var window=this;'use strict';var Zmb=function(a,b){a.Ua("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.fu(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Jg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.dT&&(b.lengthText?(e=b.lengthText||null,f=b.cw||null):b.lengthSeconds&&(e=g.xH(b.lengthSeconds),f=g.xH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.UOa(d).type;var l=b instanceof g.dT?b.isLivePlayback:null,m=b instanceof g.dT?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.JK('\u0414\u0438\u0432\u0438\u0442\u0438\u0441\u044f "$TITLE"',{TITLE:b.title}),duration:e,timestamp:f,url:b.Nk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Bs};b instanceof g.cT&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.W(),c=b.D;
g.U.call(this,{I:"a",T:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{I:"div",Na:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},X:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],Aa:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],Aa:"\u0423 \u043f\u0440\u044f\u043c\u043e\u043c\u0443 \u0435\u0444\u0456\u0440\u0456"},
{I:"div",Na:["ytp-autonav-upcoming-stamp"],Aa:"\u041d\u0435\u0437\u0430\u0431\u0430\u0440\u043e\u043c"},{I:"div",T:"ytp-autonav-list-overlay",X:[{I:"div",T:"ytp-autonav-mix-text",Aa:"\u041c\u0456\u043a\u0441"},{I:"div",T:"ytp-autonav-mix-icon"}]}]},{I:"div",Na:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Aa:"{{title}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Aa:"{{author}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
Aa:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=null;this.j=c;this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{I:"div",T:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.G=void 0;this.C=0;this.container=new g.U({I:"div",T:"ytp-autonav-endscreen-countdown-container"});g.L(this,this.container);this.container.Ga(this.element);b=a.W();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.V(a,"videodatachange",this.onVideoDataChange);this.j=new g.U({I:"div",T:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{I:"div",T:"ytp-autonav-endscreen-upnext-header"},{I:"div",T:"ytp-autonav-endscreen-upnext-alternative-header",Aa:"{{autoplayAlternativeHeader}}"},{I:"a",T:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.ea:""},X:[{I:"div",T:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},X:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],
Aa:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],Aa:"\u0423 \u043f\u0440\u044f\u043c\u043e\u043c\u0443 \u0435\u0444\u0456\u0440\u0456"},{I:"div",Na:["ytp-autonav-upcoming-stamp"],Aa:"\u041d\u0435\u0437\u0430\u0431\u0430\u0440\u043e\u043c"}]},{I:"div",T:"ytp-autonav-endscreen-video-info",X:[{I:"div",T:"ytp-autonav-endscreen-premium-badge"},{I:"div",T:"ytp-autonav-endscreen-upnext-title",Aa:"{{title}}"},{I:"div",T:"ytp-autonav-endscreen-upnext-author",Aa:"{{author}}"},{I:"div",T:"ytp-autonav-view-and-date",
Aa:"{{views_and_publish_time}}"},{I:"div",T:"ytp-autonav-author-and-view",Aa:"{{author_and_views}}"}]}]}]});g.L(this,this.j);this.j.Ga(this.container.element);d||this.V(this.j.Ha("ytp-autonav-endscreen-link-container"),"click",this.lS);this.J.xb(this.container.element,this,115127);this.J.xb(this.j.Ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({I:"div",T:"ytp-autonav-overlay"});g.L(this,this.overlay);this.overlay.Ga(this.container.element);this.B=new g.U({I:"div",T:"ytp-autonav-endscreen-button-container"});
g.L(this,this.B);this.B.Ga(this.container.element);this.cancelButton=new g.U({I:"button",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u0435 \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f"},Aa:"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438"});
g.L(this,this.cancelButton);this.cancelButton.Ga(this.B.element);this.cancelButton.Ta("click",this.I0,this);this.J.xb(this.cancelButton.element,this,115129);this.playButton=new g.U({I:"a",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u0438\u0442\u0438 \u043d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e"},
Aa:"\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u0438\u0442\u0438"});g.L(this,this.playButton);this.playButton.Ga(this.B.element);this.playButton.Ta("click",this.lS,this);this.J.xb(this.playButton.element,this,115130);this.D=new g.Ut(function(){$mb(c)},500);
g.L(this,this.D);this.kS();this.V(a,"autonavvisibility",this.kS);this.J.N("web_autonav_color_transition")&&(this.V(a,"autonavchange",this.H0),this.V(a,"onAutonavCoundownStarted",this.g7))},o6=function(a){var b=a.J.Mk(!0,a.J.isFullscreen());
g.fu(a.container.element,"ytp-autonav-endscreen-small-mode",a.wg(b));g.fu(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.WJ);g.fu(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Bf());g.fu(a.J.getRootNode(),"countdown-running",a.Qk());g.fu(a.container.element,"ytp-player-content",a.J.Bf());g.qr(a.overlay.element,{width:b.width+"px"});if(!a.Qk()){a.J.Bf()?anb(a,Math.round(bnb(a)/1E3)):anb(a);b=!!a.suggestion&&!!a.suggestion.Bs;var c=a.J.Bf()||!b;
g.fu(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.fu(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.GG(a.B,a.J.Bf());g.fu(a.element,"ytp-enable-w2w-color-transitions",cnb(a))}},$mb=function(a){var b=bnb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);anb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Qk()?a.select(!0):a.Qk()&&a.D.start()},bnb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.DB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Ss()?a.J.Ss():g.XJ(a.J.W().experiments,"autoplay_time")||1E4},cnb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},anb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ha("ytp-autonav-endscreen-upnext-header");g.of(a);if(0<=b){b=String(b);var c="\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.mf("\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(0,
d)));var e=g.lf("span");g.$t(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Bf(e,b);a.appendChild(e);a.appendChild(g.mf("\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(d+c.length)));return}}g.Bf(a,"\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435")},p6=function(a,b){g.U.call(this,{I:"div",
Na:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.U.call(this,{I:"div",
Na:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},X:[{I:"div",T:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{I:"span",T:"ytp-upnext-top",X:[{I:"span",T:"ytp-upnext-header",Aa:"\u0414\u0430\u043b\u0456"},{I:"span",T:"ytp-upnext-title",Aa:"{{title}}"},{I:"span",T:"ytp-upnext-author",Aa:"{{author}}"}]},{I:"a",T:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u0438\u0442\u0438 \u043d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e"},
X:[{I:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},X:[{I:"circle",T:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",T:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",T:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",T:"ytp-upnext-bottom",
X:[{I:"span",T:"ytp-upnext-cancel"},{I:"span",T:"ytp-upnext-paused",Aa:"\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u0435 \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u043f\u0440\u0438\u0437\u0443\u043f\u0438\u043d\u0435\u043d\u043e"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ha("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Ut(this.zG,5E3,this);this.B=0;var b=this.Ha("ytp-upnext-cancel");this.cancelButton=
new g.U({I:"button",Na:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u0435 \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f"},Aa:"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438"});g.L(this,this.cancelButton);this.cancelButton.Ta("click",this.J0,this);this.cancelButton.Ga(b);this.cancelButton&&this.api.xb(this.cancelButton.element,this,
115129);g.L(this,this.D);this.api.xb(this.element,this,18788);b=this.Ha("ytp-upnext-autoplay-icon");this.V(b,"click",this.K0);this.api.xb(b,this,115130);this.mS();this.V(a,"autonavvisibility",this.mS);this.V(a,"mdxnowautoplaying",this.P7);this.V(a,"mdxautoplaycanceled",this.Q7);g.fu(this.element,"ytp-upnext-mobile",this.api.W().B)},dnb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.DB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Ss()?a.api.Ss():g.XJ(a.api.W().experiments,"autoplay_time")||1E4},enb=function(a,b){b=dnb(a,b);
var c=Math,d=c.min;var e=(0,g.dE)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Qk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Qk()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({I:"div",T:"ytp-suggestion-panel",X:[{I:"div",Na:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Aa:"\u0406\u043d\u0448\u0456 \u0432\u0456\u0434\u0435\u043e"}]});this.S=new g.U({I:"div",T:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new n6(this.player);g.L(this,this.B);this.B.Ga(this.element);a.getVideoData().We?this.j=this.B:(this.j=new q6(a),g.IU(this.player,this.j.element,4),g.L(this,
this.j));this.overlay=new g.U({I:"div",T:"ytp-autonav-overlay-cancelled-state"});g.L(this,this.overlay);this.overlay.Ga(this.element);this.D=new g.mL(this);g.L(this,this.D);g.L(this,this.table);this.table.Ga(this.element);this.table.show();g.L(this,this.S);this.S.Ga(this.table.element);this.hide()},s6=function(a){var b=a.Bf();
b!==a.G&&(a.G=b,a.player.ra("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},t6=function(a,b){g.U.call(this,{I:"button",
Na:["ytp-watch-on-youtube-button","ytp-button"],Aa:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.wZ();2===this.buttonType&&g.bu(this.element,"ytp-continue-watching-button");this.Ta("click",this.onClick);this.Ta("videodatachange",this.wZ);g.GG(this,!0)},u6=function(a,b){p6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.ub=b;this.J.xb(this.element,this,156943);this.watchButton=new t6(a,2);g.L(this,this.watchButton);this.watchButton.Ga(this.element);this.hide()},fnb=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.U({I:"div",T:"ytp-subscribe-card",X:[{I:"img",T:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{I:"div",T:"ytp-subscribe-card-right",X:[{I:"div",T:"ytp-author-name",Aa:"{{author}}"},{I:"div",T:"html5-subscribe-button-container"}]}]});g.L(this,this.j);this.j.Ga(this.element);var b=a.getVideoData();this.subscribeButton=new g.uW("\u041f\u0456\u0434\u043f\u0438\u0441\u0430\u0442\u0438\u0441\u044f",null,"\u0412\u0456\u0434\u043f\u0438\u0441\u0430\u0442\u0438\u0441\u044f",null,!0,!1,b.Fl,
b.subscribed,"trailer-endscreen",null,a);g.L(this,this.subscribeButton);this.subscribeButton.Ga(this.j.Ha("html5-subscribe-button-container"));this.V(a,"videodatachange",this.Sa);this.Sa();this.hide()},v6=function(a){var b=a.W(),c=g.GL||g.oS?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.U.call(this,{I:"a",Na:e,Y:{href:"{{url}}",target:d?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{I:"div",T:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{I:"span",T:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},X:[{I:"span",T:"ytp-videowall-still-info-bg",X:[{I:"span",T:"ytp-videowall-still-info-content",Y:c,X:[{I:"span",T:"ytp-videowall-still-info-title",Aa:"{{title}}"},
{I:"span",T:"ytp-videowall-still-info-author",Aa:"{{author_and_views}}"},{I:"span",T:"ytp-videowall-still-info-live",Aa:"\u0423 \u043f\u0440\u044f\u043c\u043e\u043c\u0443 \u0435\u0444\u0456\u0440\u0456"},{I:"span",T:"ytp-videowall-still-info-duration",Aa:"{{duration}}"}]}]}]},{I:"span",Na:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{I:"span",T:"ytp-videowall-still-listlabel-icon"},"\u0421\u043f\u0438\u0441\u043e\u043a \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f",
{I:"span",T:"ytp-videowall-still-listlabel-length",X:[" (",{I:"span",Aa:"{{playlist_length}}"},")"]}]},{I:"span",Na:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{I:"span",T:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0456\u043a\u0441",{I:"span",T:"ytp-videowall-still-listlabel-length",Aa:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.mL(this);g.L(this,this.j);this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress);
this.j.V(a,"videodatachange",this.onVideoDataChange);a.jg(this.element,this);this.onVideoDataChange()},w6=function(a){p6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.S=!1;this.ea=null;this.B=new g.mL(this);g.L(this,this.B);this.K=new g.Ut(function(){g.bu(b.element,"ytp-show-tiles")},0);
g.L(this,this.K);var c=new g.U({I:"button",Na:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},X:[g.MG()]});g.L(this,c);c.Ga(this.element);c.Ta("click",this.O0,this);this.table=new g.DG({I:"div",T:"ytp-endscreen-content"});g.L(this,this.table);this.table.Ga(this.element);c=new g.U({I:"button",Na:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"\u0414\u0430\u043b\u0456"},X:[g.NG()]});g.L(this,c);c.Ga(this.element);c.Ta("click",this.N0,this);a.getVideoData().We?
this.j=new n6(a,!0):this.j=new q6(a);g.L(this,this.j);g.IU(this.player,this.j.element,4);a.xb(this.element,this,158789);this.hide()},x6=function(a){return g.JU(a.player)&&a.iC()&&!a.D},y6=function(a){var b=a.Bf();
b!==a.S&&(a.S=b,a.player.ra("autonavvisibility"))},z6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t6(a,1);g.L(this,this.watchButton);this.watchButton.Ga(this.element);g.Hbb(a)&&(this.j=new g.z2(a,g.qU(a)),g.L(this,this.j),this.B=new g.U({I:"div",Na:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},X:[this.j]}),g.L(this,this.B),this.j.Ga(this.B.element),this.B.Ga(this.element));a.xb(this.element,this,156914);this.hide()},jnb=function(a){g.IV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.mL(this);g.L(this,this.listeners);var c=a.W(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.dD(g.yS(c))&&d&&!g.EU(a)?(this.B=!0,this.endScreen=new u6(a,g.qU(a))):g.FU(a)?this.endScreen=new z6(a):gnb(a)?(this.D=!0,hnb(this),this.j?this.endScreen=new r6(a):this.endScreen=new w6(a)):c.Zg?this.endScreen=new fnb(a):this.endScreen=new p6(a);g.L(this,this.endScreen);g.IU(a,this.endScreen.element,4);inb(this);
this.listeners.V(a,"videodatachange",this.onVideoDataChange,this);this.listeners.V(a,g.DK("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.V(a,g.EK("endscreen"),function(e){b.onCueRangeExit(e)})},hnb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Nl&&a.C===b.We)return!1;a.j=b.Nl;a.C=b.We;return!0},gnb=function(a){a=a.W();
return a.Td&&!a.Zg},inb=function(a){a.player.lf("endscreen");
var b=a.player.getVideoData();b=new g.CK(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.CK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.xf([b,c])};
g.jY.prototype.TA=g.ea(37,function(a){this.SP!==a&&(this.SP=a,this.El())});
g.$W.prototype.Fr=g.ea(36,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.jY.prototype.Fr=g.ea(35,function(a){this.shareButton&&this.shareButton.Fr(a)});
g.VW.prototype.Er=g.ea(34,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.jY.prototype.Er=g.ea(33,function(a){this.overflowButton&&this.overflowButton.Er(a)});
g.lW.prototype.fF=g.ea(32,function(a){this.TP!==a&&(this.TP=a,this.Vp())});
g.AU.prototype.Ss=g.ea(6,function(){return this.app.Ss()});
g.b1.prototype.Ss=g.ea(5,function(){return this.getVideoData().bU});g.v(m6,g.U);m6.prototype.select=function(){this.J.uo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.DC||void 0)&&this.J.wb(this.element)};
m6.prototype.onClick=function(a){g.$U(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.v(n6,g.U);g.k=n6.prototype;g.k.IF=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.updateValue("url",this.suggestion.Nk()),o6(this))};
g.k.Qk=function(){return 0<this.C};
g.k.aB=function(){this.Qk()||(this.C=Date.now(),$mb(this),Zmb(this.J,bnb(this)),g.fu(this.J.getRootNode(),"countdown-running",this.Qk()))};
g.k.Bw=function(){this.Nr();$mb(this);var a=this.j.Ha("ytp-autonav-endscreen-upnext-header");a&&g.Bf(a,"\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435")};
g.k.Nr=function(){this.Qk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Nr()};
g.k.lS=function(a){g.$U(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.wb(this.playButton.element):a.currentTarget===this.j.Ha("ytp-autonav-endscreen-link-container")&&(a=this.j.Ha("ytp-autonav-endscreen-link-container"),this.J.Xa(a,!0),this.J.wb(a)),this.select())};
g.k.I0=function(){this.J.wb(this.cancelButton.element);g.CU(this.J,!0);this.G&&this.J.Ua("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){var c;this.G=null==(c=b.t4)?void 0:c.command};
g.k.g7=function(a){if(cnb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.FH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.FH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.FH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.FH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.FH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.FH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.fu(this.element,"ytp-w2w-animate",!0)}};
g.k.H0=function(a){this.J.N("web_autonav_color_transition")&&2!==a&&g.fu(this.element,"ytp-w2w-animate",!1)};
g.k.kS=function(){var a=this.J.Bf();this.K&&this.Ib!==a&&g.GG(this,a);o6(this);this.J.Xa(this.container.element,a);this.J.Xa(this.cancelButton.element,a);this.J.Xa(this.j.Ha("ytp-autonav-endscreen-link-container"),a);this.J.Xa(this.playButton.element,a)};
g.k.wg=function(a){return 400>a.width||459>a.height};g.v(p6,g.U);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.iC=function(){return!1};
g.k.Bf=function(){return!1};
g.k.WW=function(){return!1};g.v(q6,g.U);g.k=q6.prototype;g.k.zG=function(){this.notification&&(this.D.stop(),this.Qc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.IF=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.mS=function(){g.GG(this,this.api.Bf());this.api.Xa(this.element,this.api.Bf());this.api.Xa(this.Ha("ytp-upnext-autoplay-icon"),this.api.Bf());this.cancelButton&&this.api.Xa(this.cancelButton.element,this.api.Bf())};
g.k.Y7=function(){window.focus();this.zG()};
g.k.aB=function(a){var b=this;this.Qk()||(g.nF("a11y-announce","\u0414\u0430\u043b\u0456 "+this.suggestion.title),this.B=(0,g.dE)(),this.j=new g.Ut(function(){enb(b,a)},25),enb(this,a),Zmb(this.api,dnb(this,a)));
g.du(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Qk=function(){return!!this.j};
g.k.Bw=function(){this.Nr();this.B=(0,g.dE)();enb(this);g.bu(this.element,"ytp-upnext-autoplay-paused")};
g.k.Nr=function(){this.Qk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.W().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.zG(),this.notification=new Notification("\u0414\u0430\u043b\u0456",{body:this.suggestion.title,icon:this.suggestion.Jg()}),this.C=this.V(this.notification,"click",this.Y7),this.D.start())}this.Nr();this.api.nextVideo(!1,a)};
g.k.K0=function(a){!g.Af(this.cancelButton.element,a.target)&&g.$U(a,this.api)&&(this.api.Bf()&&this.api.wb(this.Ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.J0=function(){this.api.Bf()&&this.cancelButton&&this.api.wb(this.cancelButton.element);g.CU(this.api,!0)};
g.k.P7=function(a){this.api.getPresentingPlayerType();this.show();this.aB(a)};
g.k.Q7=function(){this.api.getPresentingPlayerType();this.Nr();this.hide()};
g.k.Ba=function(){this.Nr();this.zG();g.U.prototype.Ba.call(this)};g.v(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.D.V(this.player,"appresize",this.GB);this.D.V(this.player,"onVideoAreaChange",this.GB);this.D.V(this.player,"videodatachange",this.onVideoDataChange);this.D.V(this.player,"autonavchange",this.nS);this.D.V(this.player,"autonavcancel",this.L0);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.CU(this.player,!1);g.JU(this.player)&&this.iC()&&!this.C?(s6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.aB():3===this.videoData.autonavState&&this.j.Bw()):(g.CU(this.player,!0),s6(this));this.GB()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.Bw();s6(this)};
g.k.GB=function(){var a=this.player.Mk(!0,this.player.isFullscreen());s6(this);o6(this.B);g.fu(this.element,"ytp-autonav-cancelled-small-mode",this.wg(a));g.fu(this.element,"ytp-autonav-cancelled-tiny-mode",this.XH(a));g.fu(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.qr(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.fu(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var b=g.ET(this.videoData);b&&(this.j.IF(b),this.j!==this.B&&this.B.IF(b))}if(a&&a.length)for(b=0;b<knb.length;++b){var c=knb[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.L(this,this.videos[b]);this.videos[b].Ga(this.S.element)}}this.GB()}};
g.k.nS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Nr(),this.Ib&&this.GB()):(this.K=!0,this.Bf()&&(2===a?this.j.aB():3===a&&this.j.Bw()))};
g.k.L0=function(a){a?this.nS(1):(this.C=null,this.K=!1)};
g.k.iC=function(){return 1!==this.videoData.autonavState};
g.k.wg=function(a){return(910>a.width||459>a.height)&&!this.XH(a)&&!(400>=a.width||360>=a.height)};
g.k.XH=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Bf=function(){return this.Ib&&g.JU(this.player)&&this.iC()&&!this.C};
var knb=[1,3,2,4];g.v(t6,g.U);g.k=t6.prototype;
g.k.wZ=function(){switch(this.buttonType){case 1:var a="\u0414\u0438\u0432\u0438\u0442\u0438\u0441\u044f \u0437\u043d\u043e\u0432\u0443 \u043d\u0430 YouTube";var b=156915;break;case 2:a="\u041f\u0440\u043e\u0434\u043e\u0432\u0436\u0438\u0442\u0438 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434 \u043d\u0430 YouTube";b=156942;break;default:a="\u041f\u0440\u043e\u0434\u043e\u0432\u0436\u0438\u0442\u0438 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434 \u043d\u0430 YouTube",b=156942}this.update({content:a});
this.J.Uj(this.element)&&this.J.uC(this.element);this.J.xb(this.element,this,b)};
g.k.onClick=function(a){this.J.N("web_player_log_click_before_generating_ve_conversion_params")&&this.J.wb(this.element);g.aV(this.getVideoUrl(),this.J,a);this.J.N("web_player_log_click_before_generating_ve_conversion_params")||this.J.wb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.W();if(g.pS(b)||g.xS(b)){var c={};g.pS(b)&&g.oU(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.QP(c,b);a=g.yl(a,c)}return a};
g.k.Xa=function(){this.J.Xa(this.element,this.Ib&&this.ma)};
g.k.show=function(){g.U.prototype.show.call(this);this.Xa()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.Xa()};
g.k.lc=function(a){g.U.prototype.lc.call(this,a);this.Xa()};g.v(u6,p6);u6.prototype.show=function(){3!==this.player.getPlayerState()&&(p6.prototype.show.call(this),this.ub.TA(!0),this.ub.Fr(!0),this.J.W().Sd||this.ub.Er(!0),this.J.Xa(this.element,!0),this.watchButton.lc(!0))};
u6.prototype.hide=function(){p6.prototype.hide.call(this);this.ub.TA(!1);this.ub.Fr(!1);this.ub.Er(!1);this.J.Xa(this.element,!1);this.watchButton.lc(!1)};g.v(fnb,p6);fnb.prototype.Sa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Fl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.v(v6,g.U);v6.prototype.select=function(){this.api.uo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.DC||void 0)&&this.api.wb(this.element)};
v6.prototype.onClick=function(a){if(g.pS(this.api.W())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.wb(this.element);var b=this.suggestion.Nk(),c={};g.sRa(this.api,c,"emb_rel_end");b=g.yl(b,c);g.aV(b,this.api,a)}else g.$U(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
v6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
v6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.W();this.B=a.Qd?!1:b.D};g.v(w6,p6);g.k=w6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Yp();this.B.V(this.player,"appresize",this.Yp);this.B.V(this.player,"onVideoAreaChange",this.Yp);this.B.V(this.player,"videodatachange",this.onVideoDataChange);this.B.V(this.player,"autonavchange",this.EK);this.B.V(this.player,"autonavcancel",this.M0);a=this.videoData.autonavState;a!==this.ea&&this.EK(a);this.B.V(this.element,"transitionend",this.n9)};
g.k.destroy=function(){g.sD(this.B);g.tb(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.du(this.element,"ytp-show-tiles");this.K.stop();this.ea=this.videoData.autonavState};
g.k.iC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Ib;p6.prototype.show.call(this);g.du(this.element,"ytp-show-tiles");this.player.W().B?g.Wt(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.CU(this.player,!1);x6(this)?(y6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.aB():3===this.videoData.autonavState&&this.j.Bw()):(g.CU(this.player,!0),y6(this));a!==this.Ib&&this.player.Xa(this.element,!0)};
g.k.hide=function(){var a=this.Ib;p6.prototype.hide.call(this);this.j.Bw();y6(this);a!==this.Ib&&this.player.Xa(this.element,!1)};
g.k.n9=function(a){a.target===this.element&&this.Yp()};
g.k.Yp=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.ET(d)];if(e.length){g.bu(this.element,"ytp-endscreen-paginate");var f=this.J.Mk(!0,this.J.isFullscreen());if(a=g.qU(this.J))a=a.Lg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,w=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&w)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(w)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Ar(f,n,p);g.qr(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.IF(g.ET(this.videoData));this.j instanceof
n6&&o6(this.j);g.fu(this.element,"ytp-endscreen-takeover",x6(this));y6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.se(q+this.C,c),0!==t){r=this.stills[h];r||(r=new v6(this.player),this.stills[h]=r,f.appendChild(r.element));w=Math.floor(p*m/b);var y=Math.floor(n*l/a),C=Math.floor(p*(m+t)/b)-w-4,H=Math.floor(n*(l+t)/a)-y-4;g.wr(r.element,y,w);g.Ar(r.element,H,C);g.qr(r.element,"transitionDelay",
(m+l)/20+"s");g.fu(r.element,"ytp-videowall-still-mini",1===t);g.fu(r.element,"ytp-videowall-still-large",2<t);t=Math.max(H,C);g.fu(r.element,"ytp-videowall-still-round-large",256<=t);g.fu(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.fu(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.W(),w=g.au(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(r,q,w),g.pS(t)&&!r.api.N("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Nk(),w={},g.oU(r.api,"addEmbedsConversionTrackingParams",[w]),t=g.yl(t,g.QP(w,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.Eg(r.element,q));h++}f.ariaBusy="false";g.fu(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.yf(a.element),g.sb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.Yp())};
g.k.N0=function(){this.C+=this.stills.length;this.Yp()};
g.k.O0=function(){this.C-=this.stills.length;this.Yp()};
g.k.WW=function(){return this.j.Qk()};
g.k.EK=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Nr(),this.Ib&&this.Yp()):(this.G=!0,this.Ib&&x6(this)&&(2===a?this.j.aB():3===a&&this.j.Bw()))};
g.k.M0=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.Xa(this.stills[a].element,!0);this.EK(1)}else this.D=null,this.G=!1;this.Yp()};
g.k.Bf=function(){return this.Ib&&x6(this)};g.v(z6,p6);z6.prototype.pD=function(){var a;return null==(a=this.j)?void 0:a.pD()};
z6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.pD();g.fu(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.qU(this.player))||c.fF(!0);this.player.Xa(this.element,!0);this.watchButton.lc(!0)}};
z6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.qU(this.player))||a.fF(!1);this.player.Xa(this.element,!1);this.watchButton.lc(!1)};g.v(jnb,g.IV);g.k=jnb.prototype;g.k.fu=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.FU(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.ET(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!gnb(this.player)||d;a=a.rj||g.xS(a.La);c=this.player.OC();return d&&!a&&!c&&!b};
g.k.Bf=function(){return this.endScreen.Bf()};
g.k.Z5=function(){return this.Bf()?this.endScreen.WW():!1};
g.k.Ba=function(){this.player.lf("endscreen");g.IV.prototype.Ba.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Hb().Ue.get("heartbeat"),d=g.ET(a);!d||b.videoId!==d.videoId||a.gS?(this.player.uo(b.videoId,void 0,void 0,!0,!0,b),c&&c.eI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.IV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.IV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.fu()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){inb(this);this.D&&hnb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new w6(this.player),g.L(this,this.endScreen),g.IU(this.player,this.endScreen.element,4))};g.HV("endscreen",jnb);})(_yt_player);
